[Smartswitch] Fix the values being set for reboot_status call during smartswitch DPU reboot
During smartswitch DPU reboot we query the rebootstatus call to check the current status. This is currently failing on DPU because the RebootStatus enum is not serializable:
```
root@sonic:/home/admin# dbus-send --system --print-reply --dest=org.SONiC.HostService.reboot /org/SONiC/HostService/reboot org.SONiC.HostService.reboot.get_reboot_status
Error org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
   retval = candidate_method(self, *args, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/host_modules/reboot.py", line 218, in get_reboot_status=
   response_data = json.dumps(self.reboot_status_flag)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
   return _default_encoder.encode(obj
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
   chunks = self.iterencode(o, _one_shot=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
   return _iterencode(o, 0)
          ^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3.11/json/encoder.py", line 180, in default
   raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type RebootStatus is not JSON serializable
```
So setting it to value everywhere to fix the issue